//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.IbanService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://ced.com/MasterDataService/data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.IbanService.ValidateIbanRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.IbanService.GetBicRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.IbanService.ResolveBicRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.IbanService.PingRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateIbanRequest", Namespace="http://ced.com/IbanService/data")]
    [System.SerializableAttribute()]
    public partial class ValidateIbanRequest : Api.IbanService.RequestBase {
        
        private string IbanField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Iban {
            get {
                return this.IbanField;
            }
            set {
                if ((object.ReferenceEquals(this.IbanField, value) != true)) {
                    this.IbanField = value;
                    this.RaisePropertyChanged("Iban");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBicRequest", Namespace="http://ced.com/IbanService/data")]
    [System.SerializableAttribute()]
    public partial class GetBicRequest : Api.IbanService.RequestBase {
        
        private string BankCodeField;
        
        private string CountryCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string BankCode {
            get {
                return this.BankCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BankCodeField, value) != true)) {
                    this.BankCodeField = value;
                    this.RaisePropertyChanged("BankCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResolveBicRequest", Namespace="http://ced.com/IbanService/data")]
    [System.SerializableAttribute()]
    public partial class ResolveBicRequest : Api.IbanService.RequestBase {
        
        private string IbanField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Iban {
            get {
                return this.IbanField;
            }
            set {
                if ((object.ReferenceEquals(this.IbanField, value) != true)) {
                    this.IbanField = value;
                    this.RaisePropertyChanged("Iban");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PingRequest", Namespace="http://schemas.datacontract.org/2004/07/CED.Business.Public.Messages.Ping.Request" +
        "")]
    [System.SerializableAttribute()]
    public partial class PingRequest : Api.IbanService.RequestBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://ced.com/MasterDataService/data")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.IbanService.ValidateIbanResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.IbanService.GetBicResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.IbanService.ResolveBicResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.IbanService.PingResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long ExecutionTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ExceptionOccurredField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExceptionTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> LookupIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long ExecutionTime {
            get {
                return this.ExecutionTimeField;
            }
            set {
                if ((this.ExecutionTimeField.Equals(value) != true)) {
                    this.ExecutionTimeField = value;
                    this.RaisePropertyChanged("ExecutionTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public bool ExceptionOccurred {
            get {
                return this.ExceptionOccurredField;
            }
            set {
                if ((this.ExceptionOccurredField.Equals(value) != true)) {
                    this.ExceptionOccurredField = value;
                    this.RaisePropertyChanged("ExceptionOccurred");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string ExceptionMessage {
            get {
                return this.ExceptionMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionMessageField, value) != true)) {
                    this.ExceptionMessageField = value;
                    this.RaisePropertyChanged("ExceptionMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ExceptionTrace {
            get {
                return this.ExceptionTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.ExceptionTraceField, value) != true)) {
                    this.ExceptionTraceField = value;
                    this.RaisePropertyChanged("ExceptionTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public System.Nullable<System.Guid> LookupId {
            get {
                return this.LookupIdField;
            }
            set {
                if ((this.LookupIdField.Equals(value) != true)) {
                    this.LookupIdField = value;
                    this.RaisePropertyChanged("LookupId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidateIbanResponse", Namespace="http://ced.com/IbanService/data")]
    [System.SerializableAttribute()]
    public partial class ValidateIbanResponse : Api.IbanService.ResponseBase {
        
        private string IbanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BicField;
        
        private bool IsValidIbanField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AccountNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CountryCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BankCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BranchCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Iban {
            get {
                return this.IbanField;
            }
            set {
                if ((object.ReferenceEquals(this.IbanField, value) != true)) {
                    this.IbanField = value;
                    this.RaisePropertyChanged("Iban");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Bic {
            get {
                return this.BicField;
            }
            set {
                if ((object.ReferenceEquals(this.BicField, value) != true)) {
                    this.BicField = value;
                    this.RaisePropertyChanged("Bic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public bool IsValidIban {
            get {
                return this.IsValidIbanField;
            }
            set {
                if ((this.IsValidIbanField.Equals(value) != true)) {
                    this.IsValidIbanField = value;
                    this.RaisePropertyChanged("IsValidIban");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string AccountNumber {
            get {
                return this.AccountNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.AccountNumberField, value) != true)) {
                    this.AccountNumberField = value;
                    this.RaisePropertyChanged("AccountNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string BankName {
            get {
                return this.BankNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BankNameField, value) != true)) {
                    this.BankNameField = value;
                    this.RaisePropertyChanged("BankName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string CountryCode {
            get {
                return this.CountryCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CountryCodeField, value) != true)) {
                    this.CountryCodeField = value;
                    this.RaisePropertyChanged("CountryCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string BankAddress {
            get {
                return this.BankAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.BankAddressField, value) != true)) {
                    this.BankAddressField = value;
                    this.RaisePropertyChanged("BankAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string BankCode {
            get {
                return this.BankCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BankCodeField, value) != true)) {
                    this.BankCodeField = value;
                    this.RaisePropertyChanged("BankCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string Branch {
            get {
                return this.BranchField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchField, value) != true)) {
                    this.BranchField = value;
                    this.RaisePropertyChanged("Branch");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string BranchCode {
            get {
                return this.BranchCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.BranchCodeField, value) != true)) {
                    this.BranchCodeField = value;
                    this.RaisePropertyChanged("BranchCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetBicResponse", Namespace="http://ced.com/IbanService/data")]
    [System.SerializableAttribute()]
    public partial class GetBicResponse : Api.IbanService.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bic {
            get {
                return this.BicField;
            }
            set {
                if ((object.ReferenceEquals(this.BicField, value) != true)) {
                    this.BicField = value;
                    this.RaisePropertyChanged("Bic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResolveBicResponse", Namespace="http://ced.com/IbanService/data")]
    [System.SerializableAttribute()]
    public partial class ResolveBicResponse : Api.IbanService.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BicField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Bic {
            get {
                return this.BicField;
            }
            set {
                if ((object.ReferenceEquals(this.BicField, value) != true)) {
                    this.BicField = value;
                    this.RaisePropertyChanged("Bic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Error {
            get {
                return this.ErrorField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorField, value) != true)) {
                    this.ErrorField = value;
                    this.RaisePropertyChanged("Error");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PingResponse", Namespace="http://schemas.datacontract.org/2004/07/CED.Business.Public.Messages.Ping.Respons" +
        "e")]
    [System.SerializableAttribute()]
    public partial class PingResponse : Api.IbanService.ResponseBase {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ced.com/IbanService", ConfigurationName="IbanService.IbanService")]
    public interface IbanService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://tempuri.org/) of message PingRequest does not match the default value (http://ced.com/IbanService)
        [System.ServiceModel.OperationContractAttribute(Action="Ping", ReplyAction="http://tempuri.org/IPingService/PingResponse")]
        Api.IbanService.PingResponse1 Ping(Api.IbanService.PingRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Ping", ReplyAction="http://tempuri.org/IPingService/PingResponse")]
        System.Threading.Tasks.Task<Api.IbanService.PingResponse1> PingAsync(Api.IbanService.PingRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ValidateIban", ReplyAction="http://ced.com/IbanService/IbanService/ValidateIbanResponse")]
        Api.IbanService.ValidateIbanResponse ValidateIban(Api.IbanService.ValidateIbanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ValidateIban", ReplyAction="http://ced.com/IbanService/IbanService/ValidateIbanResponse")]
        System.Threading.Tasks.Task<Api.IbanService.ValidateIbanResponse> ValidateIbanAsync(Api.IbanService.ValidateIbanRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetBic", ReplyAction="http://ced.com/IbanService/IbanService/GetBicResponse")]
        Api.IbanService.GetBicResponse GetBic(Api.IbanService.GetBicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetBic", ReplyAction="http://ced.com/IbanService/IbanService/GetBicResponse")]
        System.Threading.Tasks.Task<Api.IbanService.GetBicResponse> GetBicAsync(Api.IbanService.GetBicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ResolveBic", ReplyAction="http://ced.com/IbanService/IbanService/ResolveBicResponse")]
        Api.IbanService.ResolveBicResponse ResolveBic(Api.IbanService.ResolveBicRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="ResolveBic", ReplyAction="http://ced.com/IbanService/IbanService/ResolveBicResponse")]
        System.Threading.Tasks.Task<Api.IbanService.ResolveBicResponse> ResolveBicAsync(Api.IbanService.ResolveBicRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ping", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PingRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Api.IbanService.PingRequest request;
        
        public PingRequest1() {
        }
        
        public PingRequest1(Api.IbanService.PingRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PingResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Api.IbanService.PingResponse PingResult;
        
        public PingResponse1() {
        }
        
        public PingResponse1(Api.IbanService.PingResponse PingResult) {
            this.PingResult = PingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IbanServiceChannel : Api.IbanService.IbanService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IbanServiceClient : System.ServiceModel.ClientBase<Api.IbanService.IbanService>, Api.IbanService.IbanService {
        
        public IbanServiceClient() {
        }
        
        public IbanServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IbanServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IbanServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IbanServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Api.IbanService.PingResponse1 Api.IbanService.IbanService.Ping(Api.IbanService.PingRequest1 request) {
            return base.Channel.Ping(request);
        }
        
        public Api.IbanService.PingResponse Ping(Api.IbanService.PingRequest request) {
            Api.IbanService.PingRequest1 inValue = new Api.IbanService.PingRequest1();
            inValue.request = request;
            Api.IbanService.PingResponse1 retVal = ((Api.IbanService.IbanService)(this)).Ping(inValue);
            return retVal.PingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Api.IbanService.PingResponse1> Api.IbanService.IbanService.PingAsync(Api.IbanService.PingRequest1 request) {
            return base.Channel.PingAsync(request);
        }
        
        public System.Threading.Tasks.Task<Api.IbanService.PingResponse1> PingAsync(Api.IbanService.PingRequest request) {
            Api.IbanService.PingRequest1 inValue = new Api.IbanService.PingRequest1();
            inValue.request = request;
            return ((Api.IbanService.IbanService)(this)).PingAsync(inValue);
        }
        
        public Api.IbanService.ValidateIbanResponse ValidateIban(Api.IbanService.ValidateIbanRequest request) {
            return base.Channel.ValidateIban(request);
        }
        
        public System.Threading.Tasks.Task<Api.IbanService.ValidateIbanResponse> ValidateIbanAsync(Api.IbanService.ValidateIbanRequest request) {
            return base.Channel.ValidateIbanAsync(request);
        }
        
        public Api.IbanService.GetBicResponse GetBic(Api.IbanService.GetBicRequest request) {
            return base.Channel.GetBic(request);
        }
        
        public System.Threading.Tasks.Task<Api.IbanService.GetBicResponse> GetBicAsync(Api.IbanService.GetBicRequest request) {
            return base.Channel.GetBicAsync(request);
        }
        
        public Api.IbanService.ResolveBicResponse ResolveBic(Api.IbanService.ResolveBicRequest request) {
            return base.Channel.ResolveBic(request);
        }
        
        public System.Threading.Tasks.Task<Api.IbanService.ResolveBicResponse> ResolveBicAsync(Api.IbanService.ResolveBicRequest request) {
            return base.Channel.ResolveBicAsync(request);
        }
    }
}
