//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.KvkValidatorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Ced.CoC", ConfigurationName="KvkValidatorService.WcfService_Ced_Coc_Integration")]
    public interface WcfService_Ced_Coc_Integration {
        
        // CODEGEN: Generating message contract since the operation GetCompanyInformation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetCompanyInformation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Api.KvkValidatorService.GetCompanyInformationResponse1 GetCompanyInformation(Api.KvkValidatorService.GetCompanyInformationRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="GetCompanyInformation", ReplyAction="*")]
        System.Threading.Tasks.Task<Api.KvkValidatorService.GetCompanyInformationResponse1> GetCompanyInformationAsync(Api.KvkValidatorService.GetCompanyInformationRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Ced.Coc.Integration.Schemas.GetCompanyInformationRequest")]
    public partial class GetCompanyInformationRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryCodeField;
        
        private string nameField;
        
        private string postalCodeField;
        
        private string houseNumberField;
        
        private string cityField;
        
        private string streetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("CountryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public string HouseNumber {
            get {
                return this.houseNumberField;
            }
            set {
                this.houseNumberField = value;
                this.RaisePropertyChanged("HouseNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Ced.Coc.Integration.Schemas.GetCompanyInformationResponse")]
    public partial class GetCompanyInformationResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        private GetCompanyInformationResponseCompany[] companiesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Company", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public GetCompanyInformationResponseCompany[] Companies {
            get {
                return this.companiesField;
            }
            set {
                this.companiesField = value;
                this.RaisePropertyChanged("Companies");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Ced.Coc.Integration.Schemas.GetCompanyInformationResponse")]
    public partial class GetCompanyInformationResponseCompany : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string coCNumberField;
        
        private string nameField;
        
        private string streetField;
        
        private string houseNumberField;
        
        private string postalCodeField;
        
        private string cityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CoCNumber {
            get {
                return this.coCNumberField;
            }
            set {
                this.coCNumberField = value;
                this.RaisePropertyChanged("CoCNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string Street {
            get {
                return this.streetField;
            }
            set {
                this.streetField = value;
                this.RaisePropertyChanged("Street");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string HouseNumber {
            get {
                return this.houseNumberField;
            }
            set {
                this.houseNumberField = value;
                this.RaisePropertyChanged("HouseNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string PostalCode {
            get {
                return this.postalCodeField;
            }
            set {
                this.postalCodeField = value;
                this.RaisePropertyChanged("PostalCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string City {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("City");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCompanyInformationRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ced.Coc.Integration.Schemas.GetCompanyInformationRequest", Order=0)]
        public Api.KvkValidatorService.GetCompanyInformationRequest GetCompanyInformationRequest;
        
        public GetCompanyInformationRequest1() {
        }
        
        public GetCompanyInformationRequest1(Api.KvkValidatorService.GetCompanyInformationRequest GetCompanyInformationRequest) {
            this.GetCompanyInformationRequest = GetCompanyInformationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCompanyInformationResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ced.Coc.Integration.Schemas.GetCompanyInformationResponse", Order=0)]
        public Api.KvkValidatorService.GetCompanyInformationResponse GetCompanyInformationResponse;
        
        public GetCompanyInformationResponse1() {
        }
        
        public GetCompanyInformationResponse1(Api.KvkValidatorService.GetCompanyInformationResponse GetCompanyInformationResponse) {
            this.GetCompanyInformationResponse = GetCompanyInformationResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WcfService_Ced_Coc_IntegrationChannel : Api.KvkValidatorService.WcfService_Ced_Coc_Integration, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfService_Ced_Coc_IntegrationClient : System.ServiceModel.ClientBase<Api.KvkValidatorService.WcfService_Ced_Coc_Integration>, Api.KvkValidatorService.WcfService_Ced_Coc_Integration {
        
        public WcfService_Ced_Coc_IntegrationClient() {
        }
        
        public WcfService_Ced_Coc_IntegrationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfService_Ced_Coc_IntegrationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfService_Ced_Coc_IntegrationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfService_Ced_Coc_IntegrationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Api.KvkValidatorService.GetCompanyInformationResponse1 Api.KvkValidatorService.WcfService_Ced_Coc_Integration.GetCompanyInformation(Api.KvkValidatorService.GetCompanyInformationRequest1 request) {
            return base.Channel.GetCompanyInformation(request);
        }
        
        public Api.KvkValidatorService.GetCompanyInformationResponse GetCompanyInformation(Api.KvkValidatorService.GetCompanyInformationRequest GetCompanyInformationRequest) {
            Api.KvkValidatorService.GetCompanyInformationRequest1 inValue = new Api.KvkValidatorService.GetCompanyInformationRequest1();
            inValue.GetCompanyInformationRequest = GetCompanyInformationRequest;
            Api.KvkValidatorService.GetCompanyInformationResponse1 retVal = ((Api.KvkValidatorService.WcfService_Ced_Coc_Integration)(this)).GetCompanyInformation(inValue);
            return retVal.GetCompanyInformationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Api.KvkValidatorService.GetCompanyInformationResponse1> Api.KvkValidatorService.WcfService_Ced_Coc_Integration.GetCompanyInformationAsync(Api.KvkValidatorService.GetCompanyInformationRequest1 request) {
            return base.Channel.GetCompanyInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<Api.KvkValidatorService.GetCompanyInformationResponse1> GetCompanyInformationAsync(Api.KvkValidatorService.GetCompanyInformationRequest GetCompanyInformationRequest) {
            Api.KvkValidatorService.GetCompanyInformationRequest1 inValue = new Api.KvkValidatorService.GetCompanyInformationRequest1();
            inValue.GetCompanyInformationRequest = GetCompanyInformationRequest;
            return ((Api.KvkValidatorService.WcfService_Ced_Coc_Integration)(this)).GetCompanyInformationAsync(inValue);
        }
    }
}
