//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VatValidatorJob.VatNumberCheckService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Ced.VatNumberCheck", ConfigurationName="VatNumberCheckService.WcfService_Ced_VatNumberCheck")]
    public interface WcfService_Ced_VatNumberCheck {
        
        // CODEGEN: Generating message contract since the operation CheckVatNumber is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="CheckVatNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        VatValidatorJob.VatNumberCheckService.CheckVatNumberResponse CheckVatNumber(VatValidatorJob.VatNumberCheckService.CheckVatNumberRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="CheckVatNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<VatValidatorJob.VatNumberCheckService.CheckVatNumberResponse> CheckVatNumberAsync(VatValidatorJob.VatNumberCheckService.CheckVatNumberRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Ced.VatNumberCheck.Schemas.CheckVatNumberRequest")]
    public partial class CheckVatNumberRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string iso2CountryCodeField;
        
        private string vatNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string Iso2CountryCode {
            get {
                return this.iso2CountryCodeField;
            }
            set {
                this.iso2CountryCodeField = value;
                this.RaisePropertyChanged("Iso2CountryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VatNumber {
            get {
                return this.vatNumberField;
            }
            set {
                this.vatNumberField = value;
                this.RaisePropertyChanged("VatNumber");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Ced.VatNumberCheck.Schemas.VatNumberCheckResponse")]
    public partial class VatNumberCheckResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string messageField;
        
        private VatNumberCheckResponseResult resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=2)]
        public VatNumberCheckResponseResult Result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("Result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2612.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://Ced.VatNumberCheck.Schemas.VatNumberCheckResponse")]
    public partial class VatNumberCheckResponseResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string countryCodeField;
        
        private string vatNumberField;
        
        private System.DateTime requestDateField;
        
        private bool isValidField;
        
        private string companyNameField;
        
        private string fullAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string CountryCode {
            get {
                return this.countryCodeField;
            }
            set {
                this.countryCodeField = value;
                this.RaisePropertyChanged("CountryCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string VatNumber {
            get {
                return this.vatNumberField;
            }
            set {
                this.vatNumberField = value;
                this.RaisePropertyChanged("VatNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime RequestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
                this.RaisePropertyChanged("RequestDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool IsValid {
            get {
                return this.isValidField;
            }
            set {
                this.isValidField = value;
                this.RaisePropertyChanged("IsValid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public string CompanyName {
            get {
                return this.companyNameField;
            }
            set {
                this.companyNameField = value;
                this.RaisePropertyChanged("CompanyName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=5)]
        public string FullAddress {
            get {
                return this.fullAddressField;
            }
            set {
                this.fullAddressField = value;
                this.RaisePropertyChanged("FullAddress");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckVatNumberRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ced.VatNumberCheck.Schemas.CheckVatNumberRequest", Order=0)]
        public VatValidatorJob.VatNumberCheckService.CheckVatNumberRequest CheckVatNumberRequest;
        
        public CheckVatNumberRequest1() {
        }
        
        public CheckVatNumberRequest1(VatValidatorJob.VatNumberCheckService.CheckVatNumberRequest CheckVatNumberRequest) {
            this.CheckVatNumberRequest = CheckVatNumberRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckVatNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://Ced.VatNumberCheck.Schemas.VatNumberCheckResponse", Order=0)]
        public VatValidatorJob.VatNumberCheckService.VatNumberCheckResponse VatNumberCheckResponse;
        
        public CheckVatNumberResponse() {
        }
        
        public CheckVatNumberResponse(VatValidatorJob.VatNumberCheckService.VatNumberCheckResponse VatNumberCheckResponse) {
            this.VatNumberCheckResponse = VatNumberCheckResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WcfService_Ced_VatNumberCheckChannel : VatValidatorJob.VatNumberCheckService.WcfService_Ced_VatNumberCheck, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfService_Ced_VatNumberCheckClient : System.ServiceModel.ClientBase<VatValidatorJob.VatNumberCheckService.WcfService_Ced_VatNumberCheck>, VatValidatorJob.VatNumberCheckService.WcfService_Ced_VatNumberCheck {
        
        public WcfService_Ced_VatNumberCheckClient() {
        }
        
        public WcfService_Ced_VatNumberCheckClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfService_Ced_VatNumberCheckClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfService_Ced_VatNumberCheckClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfService_Ced_VatNumberCheckClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VatValidatorJob.VatNumberCheckService.CheckVatNumberResponse VatValidatorJob.VatNumberCheckService.WcfService_Ced_VatNumberCheck.CheckVatNumber(VatValidatorJob.VatNumberCheckService.CheckVatNumberRequest1 request) {
            return base.Channel.CheckVatNumber(request);
        }
        
        public VatValidatorJob.VatNumberCheckService.VatNumberCheckResponse CheckVatNumber(VatValidatorJob.VatNumberCheckService.CheckVatNumberRequest CheckVatNumberRequest) {
            VatValidatorJob.VatNumberCheckService.CheckVatNumberRequest1 inValue = new VatValidatorJob.VatNumberCheckService.CheckVatNumberRequest1();
            inValue.CheckVatNumberRequest = CheckVatNumberRequest;
            VatValidatorJob.VatNumberCheckService.CheckVatNumberResponse retVal = ((VatValidatorJob.VatNumberCheckService.WcfService_Ced_VatNumberCheck)(this)).CheckVatNumber(inValue);
            return retVal.VatNumberCheckResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<VatValidatorJob.VatNumberCheckService.CheckVatNumberResponse> VatValidatorJob.VatNumberCheckService.WcfService_Ced_VatNumberCheck.CheckVatNumberAsync(VatValidatorJob.VatNumberCheckService.CheckVatNumberRequest1 request) {
            return base.Channel.CheckVatNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<VatValidatorJob.VatNumberCheckService.CheckVatNumberResponse> CheckVatNumberAsync(VatValidatorJob.VatNumberCheckService.CheckVatNumberRequest CheckVatNumberRequest) {
            VatValidatorJob.VatNumberCheckService.CheckVatNumberRequest1 inValue = new VatValidatorJob.VatNumberCheckService.CheckVatNumberRequest1();
            inValue.CheckVatNumberRequest = CheckVatNumberRequest;
            return ((VatValidatorJob.VatNumberCheckService.WcfService_Ced_VatNumberCheck)(this)).CheckVatNumberAsync(inValue);
        }
    }
}
