//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPerson : Interfaces.IIdentifiable<Guid>, Interfaces.ITrackable
    {
        public System.Guid Id { get; set; }
        public byte[] TimeStamp { get; set; }
        public System.Guid OrganizationUnitId { get; set; }
        public System.Guid ContactPersonTypeId { get; set; }
        public string FullName { get; set; }
        public short GenderId { get; set; }
        public string Email { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public bool Inactive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public string CultureCodePreferredLanguage { get; set; }
        public string CP_IntakeMethod { get; set; }
        public Nullable<System.Guid> CP_Salutation_Id { get; set; }
    
        public virtual ContactPersonType ContactPersonType { get; set; }
        public virtual OrganizationUnit OrganizationUnit { get; set; }
        public virtual Gender Gender { get; set; }
    }
}
