//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoverageProduct : Interfaces.IIdentifiable<Guid>, Interfaces.ITrackable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CoverageProduct()
        {
            this.OrganizationCoverageProducts = new HashSet<OrganizationCoverageProduct>();
        }
    
        public System.Guid Id { get; set; }
        public byte[] TimeStamp { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string SpecificInformation { get; set; }
        public bool Inactive { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string RegulationCode { get; set; }
        public string ProductNameCommercial { get; set; }
        public bool DefaultWA { get; set; }
        public string ProductCodeOriginal { get; set; }
        public Nullable<System.Guid> LocalizableEntry_Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.Guid OrganizationUnitOwner_Id { get; set; }
        public Nullable<System.Guid> CPRD_CoverageProductType_Id { get; set; }
    
        public virtual LocalizableEntry LocalizableEntry { get; set; }
        public virtual OrganizationUnit OrganizationUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrganizationCoverageProduct> OrganizationCoverageProducts { get; set; }
        public virtual CoverageProductType CoverageProductType { get; set; }
    }
}
