//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebtorOrganizationRelationsView : Interfaces.IIdentifiable<Guid>, Interfaces.ITrackable
    {
        public System.Guid Id { get; set; }
        public System.Guid OrganizationUnitId { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public System.Guid DebtorId { get; set; }
        public string DebtorNumber { get; set; }
        public string DebtorName { get; set; }
        public Nullable<System.Guid> ClientMandateId { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string DebtorPhone { get; set; }
        public string DebtorVatNumber { get; set; }
        public string DebtorChamberOfCommerceNumber { get; set; }
        public System.Guid LegalEntityId { get; set; }
        public byte[] TimeStamp { get; set; }
    }
}
