//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixedCostAgreement : Interfaces.IIdentifiable<Guid>, Interfaces.ITrackable
    {
        public System.Guid Id { get; set; }
        public byte[] TimeStamp { get; set; }
        public decimal FixedCostAmount { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<decimal> FixedCostMarginAmount { get; set; }
        public Nullable<double> OrderTotalMarginPercentage { get; set; }
        public Nullable<decimal> OrderTotalMarginAmount { get; set; }
    
        public virtual CostAgreement CostAgreement { get; set; }
    }
}
