//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class HandlingCountry : Interfaces.IIdentifiable<Guid>, Interfaces.ITrackable
    {
        public System.Guid Id { get; set; }
        public byte[] TimeStamp { get; set; }
        public System.DateTime EffectiveDate { get; set; }
        public Nullable<System.DateTime> TerminationDate { get; set; }
        public System.Guid SubContractId { get; set; }
        public string CountryCodeIso { get; set; }
        public string CurrencyCode { get; set; }
        public Nullable<short> HandlingTypeId { get; set; }
        public Nullable<System.Guid> LegalEntityId { get; set; }
        public Nullable<System.Guid> DepartmentId { get; set; }
        public Nullable<System.Guid> PartnerId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual HandlingType HandlingType { get; set; }
        public virtual Partner Partner { get; set; }
        public virtual SubContract SubContract { get; set; }
        public virtual Department Department { get; set; }
        public virtual LegalEntity LegalEntity { get; set; }
    }
}
