//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternationalAssistanceGroup : Interfaces.IIdentifiable<Guid>, Interfaces.ITrackable
    {
        public System.Guid Id { get; set; }
        public byte[] TimeStamp { get; set; }
        public string ExternalCode { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.Guid> InternationalAssistanceGroupTypeId { get; set; }
        public Nullable<bool> Inactive { get; set; }
        public string CultureCodePreferredLanguage { get; set; }
    
        public virtual InternationalAssistanceGroupType InternationalAssistanceGroupType { get; set; }
        public virtual OrganizationUnit OrganizationUnit { get; set; }
    }
}
