//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Journal : Interfaces.IIdentifiable<String>, Interfaces.ITrackable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Journal()
        {
            this.CreditPurchaseLegalEntities = new HashSet<LegalEntity>();
            this.CreditSaleLegalEntities = new HashSet<LegalEntity>();
            this.PurchaseLegalEntities = new HashSet<LegalEntity>();
            this.SaleLegalEntities = new HashSet<LegalEntity>();
        }
    
        public string Id { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Abbreviation { get; set; }
        public string Description { get; set; }
        public string CurrencyCode { get; set; }
        public string JournalTypeId { get; set; }
        public string GeneralLedgerId { get; set; }
        public Nullable<System.Guid> BankAccountId { get; set; }
        public System.Guid LegalEntityId { get; set; }
        public string ExactAdministration { get; set; }
        public string ExactJournal { get; set; }
        public bool Inactive { get; set; }
        public Nullable<System.Guid> LocalizableEntryId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
    
        public virtual LegalEntity LegalEntity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegalEntity> CreditPurchaseLegalEntities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegalEntity> CreditSaleLegalEntities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegalEntity> PurchaseLegalEntities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LegalEntity> SaleLegalEntities { get; set; }
        public virtual GeneralLedger GeneralLedger { get; set; }
        public virtual BankAccount BankAccount { get; set; }
        public virtual JournalType JournalType { get; set; }
        public virtual LocalizableEntry LocalizableEntry { get; set; }
    }
}
