//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LegalEntitiesView : Interfaces.IIdentifiable<Guid>, Interfaces.ITrackable
    {
        public System.Guid Id { get; set; }
        public string LegalEntityCode { get; set; }
        public string LegalEntityAbbreviation { get; set; }
        public string LegalEntityName { get; set; }
        public string ExactAdministration { get; set; }
        public string CurrencyCode { get; set; }
        public string StreetName { get; set; }
        public string HouseNo { get; set; }
        public string HouseNoAddition { get; set; }
        public string PostalCode { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string CountryCode { get; set; }
        public bool Inactive { get; set; }
        public string VatNumber { get; set; }
        public Nullable<System.Guid> GeneralSupplierId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public byte[] TimeStamp { get; set; }
    }
}
