//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MasterDataContext : DbContext
    {
        public MasterDataContext()
            : base("name=MasterDataContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tenant> Tenants { get; set; }
        public virtual DbSet<OrganizationType> OrganizationTypes { get; set; }
        public virtual DbSet<CollectionCode> CollectionCodes { get; set; }
        public virtual DbSet<OrganizationUnit> OrganizationUnits { get; set; }
        public virtual DbSet<OrganizationGroup> OrganizationGroups { get; set; }
        public virtual DbSet<HierarchyType> HierarchyTypes { get; set; }
        public virtual DbSet<Address> Addresses { get; set; }
        public virtual DbSet<PostOfficeBox> PostOfficeBoxes { get; set; }
        public virtual DbSet<LocalizableEntry> LocalizableEntries { get; set; }
        public virtual DbSet<LocalizableType> LocalizableTypes { get; set; }
        public virtual DbSet<LocalizedEntry> LocalizedEntries { get; set; }
        public virtual DbSet<Agent> Agents { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Mandate> Mandates { get; set; }
        public virtual DbSet<Partner> Partners { get; set; }
        public virtual DbSet<Repairer> Repairers { get; set; }
        public virtual DbSet<Supplier> Suppliers { get; set; }
        public virtual DbSet<OrganizationHierarchy> OrganizationHierarchies { get; set; }
        public virtual DbSet<TaxType> TaxTypes { get; set; }
        public virtual DbSet<TaxCode> TaxCodes { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<ProductGroup> ProductGroups { get; set; }
        public virtual DbSet<DamageReason> DamageReasons { get; set; }
        public virtual DbSet<BankAccount> BankAccounts { get; set; }
        public virtual DbSet<OrganizationAccount> OrganizationAccounts { get; set; }
        public virtual DbSet<HandlingCountry> HandlingCountries { get; set; }
        public virtual DbSet<HandlingType> HandlingTypes { get; set; }
        public virtual DbSet<MainContract> MainContracts { get; set; }
        public virtual DbSet<SubContract> SubContracts { get; set; }
        public virtual DbSet<OrganizationCode> OrganizationCodes { get; set; }
        public virtual DbSet<OrganizationCodeType> OrganizationCodeTypes { get; set; }
        public virtual DbSet<ContactPersonType> ContactPersonTypes { get; set; }
        public virtual DbSet<ContactPerson> ContactPersons { get; set; }
        public virtual DbSet<Gender> Genders { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<ServiceGroup> ServiceGroups { get; set; }
        public virtual DbSet<Service> Services { get; set; }
        public virtual DbSet<ClientMandate> ClientMandates { get; set; }
        public virtual DbSet<RepairerSkill> RepairerSkills { get; set; }
        public virtual DbSet<SupplierService> SupplierServices { get; set; }
        public virtual DbSet<InsuranceCoverage> InsuranceCoverages { get; set; }
        public virtual DbSet<InsuranceObject> InsuranceObjects { get; set; }
        public virtual DbSet<ProductDamageReason> ProductDamageReasons { get; set; }
        public virtual DbSet<ProductInsuranceCoverage> ProductInsuranceCoverages { get; set; }
        public virtual DbSet<ProductInsuranceObject> ProductInsuranceObjects { get; set; }
        public virtual DbSet<ProductWorkActivity> ProductWorkActivities { get; set; }
        public virtual DbSet<WorkActivity> WorkActivities { get; set; }
        public virtual DbSet<WorkActivityOption> WorkActivityOptions { get; set; }
        public virtual DbSet<ActivityOption> ActivityOptions { get; set; }
        public virtual DbSet<ActivityExecution> ActivityExecutions { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<ServiceApplication> ServiceApplications { get; set; }
        public virtual DbSet<ProductApplication> ProductApplications { get; set; }
        public virtual DbSet<OrganizationUnitValidationStatus> OrganizationUnitValidationStatuses { get; set; }
        public virtual DbSet<OrganizationUnitValidationStatusHistory> OrganizationUnitValidationStatusHistories { get; set; }
        public virtual DbSet<DamageReasonRelation> DamageReasonRelations { get; set; }
        public virtual DbSet<WorkActivityRelation> WorkActivityRelations { get; set; }
        public virtual DbSet<InsuranceObjectHierarchy> InsuranceObjectHierarchies { get; set; }
        public virtual DbSet<InsuranceCoverageHierarchy> InsuranceCoverageHierarchies { get; set; }
        public virtual DbSet<DamageLocation> DamageLocations { get; set; }
        public virtual DbSet<Brand> Brands { get; set; }
        public virtual DbSet<ModelProduct> ModelProducts { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<ModelSpecification> ModelSpecifications { get; set; }
        public virtual DbSet<Specification> Specifications { get; set; }
        public virtual DbSet<ClientAgent> ClientAgents { get; set; }
        public virtual DbSet<ProductExclusion> ProductExclusions { get; set; }
        public virtual DbSet<BusinessHour> BusinessHours { get; set; }
        public virtual DbSet<PaintType> PaintTypes { get; set; }
        public virtual DbSet<Status> Statuses { get; set; }
        public virtual DbSet<Fuel> Fuels { get; set; }
        public virtual DbSet<Transmission> Transmissions { get; set; }
        public virtual DbSet<MeterReadingDetermined> MeterReadingDetermineds { get; set; }
        public virtual DbSet<MeterReadingQuantity> MeterReadingQuantities { get; set; }
        public virtual DbSet<InputMethod> InputMethods { get; set; }
        public virtual DbSet<Color> Colors { get; set; }
        public virtual DbSet<Chain> Chains { get; set; }
        public virtual DbSet<RoleCode> RoleCodes { get; set; }
        public virtual DbSet<SalesOrderApprovalSetting> SalesOrderApprovalSettings { get; set; }
        public virtual DbSet<CorrespondenceMethod> CorrespondenceMethods { get; set; }
        public virtual DbSet<InsuranceObjectDamageLocation> InsuranceObjectDamageLocations { get; set; }
        public virtual DbSet<TimeWindowList> TimeWindowLists { get; set; }
        public virtual DbSet<TimeWindow> TimeWindows { get; set; }
        public virtual DbSet<ContactType> ContactTypes { get; set; }
        public virtual DbSet<OrganizationContact> OrganizationContacts { get; set; }
        public virtual DbSet<Currency> Currencies { get; set; }
        public virtual DbSet<SepaCountry> SepaCountries { get; set; }
        public virtual DbSet<Country> Countries { get; set; }
        public virtual DbSet<CurrencyCountry> CurrencyCountries { get; set; }
        public virtual DbSet<BusinessUnit> BusinessUnits { get; set; }
        public virtual DbSet<DepartmentOffice> DepartmentOffices { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<FiscalEntity> FiscalEntities { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<LegalEntity> LegalEntities { get; set; }
        public virtual DbSet<LegalEntityType> LegalEntityTypes { get; set; }
        public virtual DbSet<Office> Offices { get; set; }
        public virtual DbSet<ProductLine> ProductLines { get; set; }
        public virtual DbSet<Region> Regions { get; set; }
        public virtual DbSet<AddressType> AddressTypes { get; set; }
        public virtual DbSet<AlarmCenter> AlarmCenters { get; set; }
        public virtual DbSet<AssistanceLocationType> AssistanceLocationTypes { get; set; }
        public virtual DbSet<AssistancePlanType> AssistancePlanTypes { get; set; }
        public virtual DbSet<CostAgreement> CostAgreements { get; set; }
        public virtual DbSet<CostAgreementType> CostAgreementTypes { get; set; }
        public virtual DbSet<CostSettlementLine> CostSettlementLines { get; set; }
        public virtual DbSet<CostSettlement> CostSettlements { get; set; }
        public virtual DbSet<EuropeanUnionCountry> EuropeanUnionCountries { get; set; }
        public virtual DbSet<FixedCostAgreement> FixedCostAgreements { get; set; }
        public virtual DbSet<OrganizationAddress> OrganizationAddresses { get; set; }
        public virtual DbSet<OrganizationNote> OrganizationNotes { get; set; }
        public virtual DbSet<ServiceCode> ServiceCodes { get; set; }
        public virtual DbSet<ServiceCodeType> ServiceCodeTypes { get; set; }
        public virtual DbSet<UnitOfMeasure> UnitOfMeasures { get; set; }
        public virtual DbSet<DamageReasonType> DamageReasonTypes { get; set; }
        public virtual DbSet<InsuranceCoverageType> InsuranceCoverageTypes { get; set; }
        public virtual DbSet<InsuranceObjectType> InsuranceObjectTypes { get; set; }
        public virtual DbSet<ProductHierarchy> ProductHierarchies { get; set; }
        public virtual DbSet<ProductProperty> ProductProperties { get; set; }
        public virtual DbSet<ValuationPrinciple> ValuationPrinciples { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<CostCenter> CostCenters { get; set; }
        public virtual DbSet<CostUnit> CostUnits { get; set; }
        public virtual DbSet<GeneralLedger> GeneralLedgers { get; set; }
        public virtual DbSet<Journal> Journals { get; set; }
        public virtual DbSet<JournalType> JournalTypes { get; set; }
        public virtual DbSet<DocumentType> DocumentTypes { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
        public virtual DbSet<AssistancePlanStatus> AssistancePlanStatuses { get; set; }
        public virtual DbSet<BankAccountAttachment> BankAccountAttachments { get; set; }
        public virtual DbSet<BankAccountValidation> BankAccountValidations { get; set; }
        public virtual DbSet<InternationalAssistanceGroup> InternationalAssistanceGroups { get; set; }
        public virtual DbSet<InternationalAssistanceGroupType> InternationalAssistanceGroupTypes { get; set; }
        public virtual DbSet<OrganizationLabel> OrganizationLabels { get; set; }
        public virtual DbSet<OrganizationLabelType> OrganizationLabelTypes { get; set; }
        public virtual DbSet<SupplierBrand> SupplierBrands { get; set; }
        public virtual DbSet<VatNumberValidation> VatNumberValidations { get; set; }
        public virtual DbSet<VatNumberValidationSource> VatNumberValidationSources { get; set; }
        public virtual DbSet<OrganizationApplication> OrganizationApplications { get; set; }
        public virtual DbSet<OrganizationTaxCode> OrganizationTaxCodes { get; set; }
        public virtual DbSet<AuthorizationGroupRole> AuthorizationGroupRoles { get; set; }
        public virtual DbSet<AuthorizationRoleInheritance> AuthorizationRoleInheritances { get; set; }
        public virtual DbSet<AuthorizationRole> AuthorizationRoles { get; set; }
        public virtual DbSet<AuthorizationRoleType> AuthorizationRoleTypes { get; set; }
        public virtual DbSet<EmployeeAuthorization> EmployeeAuthorizations { get; set; }
        public virtual DbSet<OrganizationAccountAttachment> OrganizationAccountAttachments { get; set; }
        public virtual DbSet<OrganizationAccountValidation> OrganizationAccountValidations { get; set; }
        public virtual DbSet<AuthorizationRoleInheritanceView> AuthorizationRoleInheritanceViews { get; set; }
        public virtual DbSet<AuthorizationRolesView> AuthorizationRolesViews { get; set; }
        public virtual DbSet<EmployeeAuthorizationsView> EmployeeAuthorizationsViews { get; set; }
        public virtual DbSet<SupplierTaxCodesView> SupplierTaxCodesViews { get; set; }
        public virtual DbSet<SalesOrderApprovalSettingsView> SalesOrderApprovalSettingsViews { get; set; }
        public virtual DbSet<OrganizationVatValidation> OrganizationVatValidations { get; set; }
        public virtual DbSet<DepartmentsView> DepartmentsViews { get; set; }
        public virtual DbSet<EmployeesView> EmployeesViews { get; set; }
        public virtual DbSet<ClientInsuranceProduct> ClientInsuranceProducts { get; set; }
        public virtual DbSet<ClientInvoiceRecipient> ClientInvoiceRecipients { get; set; }
        public virtual DbSet<LegalEntitiesView> LegalEntitiesViews { get; set; }
        public virtual DbSet<DocumentNumber> DocumentNumbers { get; set; }
        public virtual DbSet<NextNumber> NextNumbers { get; set; }
        public virtual DbSet<CreditorAttribute> CreditorAttributes { get; set; }
        public virtual DbSet<CreditorOrganizationRelation> CreditorOrganizationRelations { get; set; }
        public virtual DbSet<Creditor> Creditors { get; set; }
        public virtual DbSet<Insurer> Insurers { get; set; }
        public virtual DbSet<DocumentTypeDepartment> DocumentTypeDepartments { get; set; }
        public virtual DbSet<PaymentCondition> PaymentConditions { get; set; }
        public virtual DbSet<InsurerAlarmCenter> InsurerAlarmCenters { get; set; }
        public virtual DbSet<MandateAlarmCenter> MandateAlarmCenters { get; set; }
        public virtual DbSet<TimeSlot> TimeSlots { get; set; }
        public virtual DbSet<TimeTable> TimeTables { get; set; }
        public virtual DbSet<TimeTableSlot> TimeTableSlots { get; set; }
        public virtual DbSet<AppointmentTimeSlot> AppointmentTimeSlots { get; set; }
        public virtual DbSet<CreditorAccount> CreditorAccounts { get; set; }
        public virtual DbSet<DebtorAccount> DebtorAccounts { get; set; }
        public virtual DbSet<Debtor> Debtors { get; set; }
        public virtual DbSet<OrganizationPaymentCondition> OrganizationPaymentConditions { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<OrganizationPaymentMethod> OrganizationPaymentMethods { get; set; }
        public virtual DbSet<DebtorAttribute> DebtorAttributes { get; set; }
        public virtual DbSet<DebtorOrganizationRelation> DebtorOrganizationRelations { get; set; }
        public virtual DbSet<ContractParty> ContractParties { get; set; }
        public virtual DbSet<ConvenantParty> ConvenantParties { get; set; }
        public virtual DbSet<CoverageProduct> CoverageProducts { get; set; }
        public virtual DbSet<OrganizationCoverageProduct> OrganizationCoverageProducts { get; set; }
        public virtual DbSet<OrganizationCoverageProductsExtension> OrganizationCoverageProductsExtensions { get; set; }
        public virtual DbSet<OrganizationUnitWithCurrentStatus> OrganizationUnitWithCurrentStatus { get; set; }
        public virtual DbSet<InvoiceDeliveryMethod> InvoiceDeliveryMethods { get; set; }
        public virtual DbSet<InvoiceDeliveryMethodType> InvoiceDeliveryMethodTypes { get; set; }
        public virtual DbSet<ClientPreferredSupplier> ClientPreferredSuppliers { get; set; }
        public virtual DbSet<RoadAuthority> RoadAuthorities { get; set; }
        public virtual DbSet<RoadAuthorityCode> RoadAuthorityCodes { get; set; }
        public virtual DbSet<RoadAuthorityType> RoadAuthorityTypes { get; set; }
        public virtual DbSet<LeasingCompany> LeasingCompanies { get; set; }
        public virtual DbSet<LeasingCompanyAlarmCenter> LeasingCompanyAlarmCenters { get; set; }
        public virtual DbSet<BusinessUnitsView> BusinessUnitsViews { get; set; }
        public virtual DbSet<DebtorOrganizationRelationsView> DebtorOrganizationRelationsViews { get; set; }
        public virtual DbSet<Bank> Banks { get; set; }
        public virtual DbSet<IbanCountry> IbanCountries { get; set; }
        public virtual DbSet<CoverageProductType> CoverageProductTypes { get; set; }
        public virtual DbSet<ProductClassification> ProductClassifications { get; set; }
        public virtual DbSet<DefaultTemplate> DefaultTemplates { get; set; }
        public virtual DbSet<Template> Templates { get; set; }
        public virtual DbSet<TemplateType> TemplateTypes { get; set; }
        public virtual DbSet<Setting> Settings { get; set; }
        public virtual DbSet<ClientTemplate> ClientTemplates { get; set; }
        public virtual DbSet<DebtorTemplate> DebtorTemplates { get; set; }
    }
}
