//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrganizationUnitWithCurrentStatus : Interfaces.IIdentifiable<Guid>, Interfaces.ITrackable
    {
        public System.Guid Id { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Code { get; set; }
        public string ShortName { get; set; }
        public string LongName { get; set; }
        public string PorCode { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool Inactive { get; set; }
        public Nullable<System.Guid> OrganizationTypeId { get; set; }
        public Nullable<System.Guid> HierarchyTypeId { get; set; }
        public Nullable<System.Guid> AddressId { get; set; }
        public Nullable<System.Guid> PostOfficeBoxId { get; set; }
        public Nullable<System.Guid> OrganizationGroupId { get; set; }
        public Nullable<System.Guid> CollectionCodeId { get; set; }
        public string Website { get; set; }
        public string Email { get; set; }
        public string VatNumber { get; set; }
        public string ChamberOfCommerceNumber { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public string Phone { get; set; }
        public Nullable<System.Guid> Tenant_Id { get; set; }
        public string SalesTaxCodeId { get; set; }
        public string PurchaseTaxCodeId { get; set; }
        public string Fax { get; set; }
        public string LongName2 { get; set; }
        public string LongName3 { get; set; }
        public string ValidationStatusId { get; set; }
        public string ListOfApplications { get; set; }
    }
}
