//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product : Interfaces.IIdentifiable<Guid>, Interfaces.ITrackable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.SubContracts = new HashSet<SubContract>();
            this.ProductDamageReasons = new HashSet<ProductDamageReason>();
            this.ProductInsuranceCoverages = new HashSet<ProductInsuranceCoverage>();
            this.ProductInsuranceObjects = new HashSet<ProductInsuranceObject>();
            this.ProductWorkActivities = new HashSet<ProductWorkActivity>();
            this.ProductExclusions = new HashSet<ProductExclusion>();
            this.ModelProducts = new HashSet<ModelProduct>();
            this.ProductApplications = new HashSet<ProductApplication>();
            this.ProductHierarchies = new HashSet<ProductHierarchy>();
            this.AppointmentTimeSlots = new HashSet<AppointmentTimeSlot>();
            this.Services = new HashSet<Service>();
            this.DebtorOrganizationRelations = new HashSet<DebtorOrganizationRelation>();
        }
    
        public System.Guid Id { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Code { get; set; }
        public string ShortName { get; set; }
        public string LongName { get; set; }
        public bool Inactive { get; set; }
        public System.Guid ProductGroupId { get; set; }
        public Nullable<System.Guid> DepartmentId { get; set; }
        public string SalesLedgerAccount { get; set; }
        public string PurchaseLedgerAccount { get; set; }
        public string SalesTaxCodeId { get; set; }
        public string PurchaseTaxCodeId { get; set; }
        public string ConsolidationCreditorNumber { get; set; }
        public string LedgerAccount { get; set; }
        public bool PurchaseTaxIncluded { get; set; }
        public Nullable<System.Guid> LocalizableEntryId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public bool PurchaseTaxApplicable { get; set; }
        public bool IsTransitoryItem { get; set; }
        public Nullable<System.Guid> ProductClassification_Id { get; set; }
        public Nullable<System.Guid> PRD_ProductType_Id { get; set; }
    
        public virtual LocalizableEntry LocalizableEntry { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
        public virtual OrganizationUnit OrganizationUnit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SubContract> SubContracts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDamageReason> ProductDamageReasons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInsuranceCoverage> ProductInsuranceCoverages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductInsuranceObject> ProductInsuranceObjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductWorkActivity> ProductWorkActivities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductExclusion> ProductExclusions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ModelProduct> ModelProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductApplication> ProductApplications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductHierarchy> ProductHierarchies { get; set; }
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppointmentTimeSlot> AppointmentTimeSlots { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Service> Services { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DebtorOrganizationRelation> DebtorOrganizationRelations { get; set; }
        public virtual ProductClassification ProductClassification { get; set; }
    }
}
