//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductExclusion : Interfaces.IIdentifiable<Guid>, Interfaces.ITrackable
    {
        public System.Guid Id { get; set; }
        public byte[] TimeStamp { get; set; }
        public Nullable<System.Guid> ProductId { get; set; }
        public Nullable<System.Guid> WorkActivityId { get; set; }
        public Nullable<System.Guid> InsuranceObjectId { get; set; }
        public Nullable<System.Guid> DamageReasonId { get; set; }
        public Nullable<System.Guid> InsuranceCoverageId { get; set; }
        public bool Inactive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
        public Nullable<System.Guid> PEX_ActivityExecution_Id { get; set; }
        public Nullable<System.Guid> PEX_ReportingForm_Id { get; set; }
        public Nullable<bool> PEX_IsPrivate { get; set; }
        public Nullable<bool> PEX_IsBusiness { get; set; }
    
        public virtual DamageReason DamageReason { get; set; }
        public virtual InsuranceCoverage InsuranceCoverage { get; set; }
        public virtual InsuranceObject InsuranceObject { get; set; }
        public virtual Product Product { get; set; }
        public virtual WorkActivity WorkActivity { get; set; }
    }
}
