//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Setting : Interfaces.IIdentifiable<Int16>, Interfaces.ITrackable
    {
        public short Id { get; set; }
        public byte[] TimeStamp { get; set; }
        public string Key { get; set; }
        public string Value { get; set; }
        public string Context { get; set; }
        public bool IsSystem { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime LastModifiedDate { get; set; }
        public string LastModifiedBy { get; set; }
    }
}
