//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Api.DmsService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestBase", Namespace="http://schemas.datacontract.org/2004/07/Ced.DocumentArchive.DmsService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.DmsService.GetDocumentByIdRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.DmsService.GetDocumentsByIndecesRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.DmsService.SaveDocumentRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.DmsService.UpdateDocumentRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.DmsService.DuplicateDocumentRequest))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.DmsService.PingRequest))]
    public partial class RequestBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDocumentByIdRequest", Namespace="http://schemas.datacontract.org/2004/07/Ced.DocumentArchive.DmsService.Messages.R" +
        "equest")]
    [System.SerializableAttribute()]
    public partial class GetDocumentByIdRequest : Api.DmsService.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDocumentsByIndecesRequest", Namespace="http://schemas.datacontract.org/2004/07/Ced.DocumentArchive.DmsService.Messages.R" +
        "equest")]
    [System.SerializableAttribute()]
    public partial class GetDocumentsByIndecesRequest : Api.DmsService.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.DmsService.ArchiveIndex[] IndecesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.DmsService.ArchiveIndex[] Indeces {
            get {
                return this.IndecesField;
            }
            set {
                if ((object.ReferenceEquals(this.IndecesField, value) != true)) {
                    this.IndecesField = value;
                    this.RaisePropertyChanged("Indeces");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveDocumentRequest", Namespace="http://schemas.datacontract.org/2004/07/Ced.DocumentArchive.DmsService.Messages.R" +
        "equest")]
    [System.SerializableAttribute()]
    public partial class SaveDocumentRequest : Api.DmsService.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.DmsService.Document DocumentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.DmsService.Document Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdateDocumentRequest", Namespace="http://schemas.datacontract.org/2004/07/Ced.DocumentArchive.DmsService.Messages.R" +
        "equest")]
    [System.SerializableAttribute()]
    public partial class UpdateDocumentRequest : Api.DmsService.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.DmsService.ArchiveIndex[] IndexesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.DmsService.ArchiveIndex[] Indexes {
            get {
                return this.IndexesField;
            }
            set {
                if ((object.ReferenceEquals(this.IndexesField, value) != true)) {
                    this.IndexesField = value;
                    this.RaisePropertyChanged("Indexes");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DuplicateDocumentRequest", Namespace="http://schemas.datacontract.org/2004/07/Ced.DocumentArchive.DmsService.Messages.R" +
        "equest")]
    [System.SerializableAttribute()]
    public partial class DuplicateDocumentRequest : Api.DmsService.RequestBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.DmsService.ArchiveIndex[] IndexesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.DmsService.ArchiveIndex[] Indexes {
            get {
                return this.IndexesField;
            }
            set {
                if ((object.ReferenceEquals(this.IndexesField, value) != true)) {
                    this.IndexesField = value;
                    this.RaisePropertyChanged("Indexes");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PingRequest", Namespace="http://schemas.datacontract.org/2004/07/Ced.DocumentArchive.DmsService.Messages.R" +
        "equest")]
    [System.SerializableAttribute()]
    public partial class PingRequest : Api.DmsService.RequestBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArchiveIndex", Namespace="http://schemas.datacontract.org/2004/07/Ced.DocumentArchive.DmsService.Messages")]
    [System.SerializableAttribute()]
    public partial class ArchiveIndex : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Key {
            get {
                return this.KeyField;
            }
            set {
                if ((object.ReferenceEquals(this.KeyField, value) != true)) {
                    this.KeyField = value;
                    this.RaisePropertyChanged("Key");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value {
            get {
                return this.ValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ValueField, value) != true)) {
                    this.ValueField = value;
                    this.RaisePropertyChanged("Value");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Document", Namespace="http://schemas.datacontract.org/2004/07/Ced.DocumentArchive.DmsService.Messages.E" +
        "ntities")]
    [System.SerializableAttribute()]
    public partial class Document : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.DmsService.ArchiveIndex[] IndexesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.DmsService.Page[] PagesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.DmsService.ArchiveIndex[] Indexes {
            get {
                return this.IndexesField;
            }
            set {
                if ((object.ReferenceEquals(this.IndexesField, value) != true)) {
                    this.IndexesField = value;
                    this.RaisePropertyChanged("Indexes");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.DmsService.Page[] Pages {
            get {
                return this.PagesField;
            }
            set {
                if ((object.ReferenceEquals(this.PagesField, value) != true)) {
                    this.PagesField = value;
                    this.RaisePropertyChanged("Pages");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Page", Namespace="http://schemas.datacontract.org/2004/07/Ced.DocumentArchive.DmsService.Messages")]
    [System.SerializableAttribute()]
    public partial class Page : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private byte[] ContentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FileNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> IndexedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] Content {
            get {
                return this.ContentField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentField, value) != true)) {
                    this.ContentField = value;
                    this.RaisePropertyChanged("Content");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName {
            get {
                return this.FileNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FileNameField, value) != true)) {
                    this.FileNameField = value;
                    this.RaisePropertyChanged("FileName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> IndexedDate {
            get {
                return this.IndexedDateField;
            }
            set {
                if ((this.IndexedDateField.Equals(value) != true)) {
                    this.IndexedDateField = value;
                    this.RaisePropertyChanged("IndexedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mime {
            get {
                return this.MimeField;
            }
            set {
                if ((object.ReferenceEquals(this.MimeField, value) != true)) {
                    this.MimeField = value;
                    this.RaisePropertyChanged("Mime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string DocumentType {
            get {
                return this.DocumentTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentTypeField, value) != true)) {
                    this.DocumentTypeField = value;
                    this.RaisePropertyChanged("DocumentType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseBase", Namespace="http://schemas.datacontract.org/2004/07/Ced.DocumentArchive.DmsService")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.DmsService.GetDocumentByIdResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.DmsService.GetDocumentsByIndecesResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.DmsService.SaveDocumentResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.DmsService.UpateDocumentResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.DmsService.DuplicateDocumentResponse))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Api.DmsService.PingResponse))]
    public partial class ResponseBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDocumentByIdResponse", Namespace="http://schemas.datacontract.org/2004/07/Ced.DocumentArchive.DmsService.Messages.R" +
        "esponse")]
    [System.SerializableAttribute()]
    public partial class GetDocumentByIdResponse : Api.DmsService.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.DmsService.Document DocumentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.DmsService.Document Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GetDocumentsByIndecesResponse", Namespace="http://schemas.datacontract.org/2004/07/Ced.DocumentArchive.DmsService.Messages.R" +
        "esponse")]
    [System.SerializableAttribute()]
    public partial class GetDocumentsByIndecesResponse : Api.DmsService.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Api.DmsService.Document[] DocumentsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Api.DmsService.Document[] Documents {
            get {
                return this.DocumentsField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentsField, value) != true)) {
                    this.DocumentsField = value;
                    this.RaisePropertyChanged("Documents");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaveDocumentResponse", Namespace="http://schemas.datacontract.org/2004/07/Ced.DocumentArchive.DmsService.Messages.R" +
        "esponse")]
    [System.SerializableAttribute()]
    public partial class SaveDocumentResponse : Api.DmsService.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpateDocumentResponse", Namespace="http://schemas.datacontract.org/2004/07/Ced.DocumentArchive.DmsService.Messages.R" +
        "esponse")]
    [System.SerializableAttribute()]
    public partial class UpateDocumentResponse : Api.DmsService.ResponseBase {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DuplicateDocumentResponse", Namespace="http://schemas.datacontract.org/2004/07/Ced.DocumentArchive.DmsService.Messages.R" +
        "esponse")]
    [System.SerializableAttribute()]
    public partial class DuplicateDocumentResponse : Api.DmsService.ResponseBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PingResponse", Namespace="http://schemas.datacontract.org/2004/07/Ced.DocumentArchive.DmsService.Messages.R" +
        "esponse")]
    [System.SerializableAttribute()]
    public partial class PingResponse : Api.DmsService.ResponseBase {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Ced.DocumentArchive.DmsService", ConfigurationName="DmsService.IDmsService")]
    public interface IDmsService {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://tempuri.org/) of message PingRequest does not match the default value (http://Ced.DocumentArchive.DmsService)
        [System.ServiceModel.OperationContractAttribute(Action="Ping", ReplyAction="http://tempuri.org/IPingService/PingResponse")]
        Api.DmsService.PingResponse1 Ping(Api.DmsService.PingRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="Ping", ReplyAction="http://tempuri.org/IPingService/PingResponse")]
        System.Threading.Tasks.Task<Api.DmsService.PingResponse1> PingAsync(Api.DmsService.PingRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Ced.DocumentArchive.DmsService/IDmsService/GetDocumentById", ReplyAction="http://Ced.DocumentArchive.DmsService/IDmsService/GetDocumentByIdResponse")]
        Api.DmsService.GetDocumentByIdResponse GetDocumentById(Api.DmsService.GetDocumentByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Ced.DocumentArchive.DmsService/IDmsService/GetDocumentById", ReplyAction="http://Ced.DocumentArchive.DmsService/IDmsService/GetDocumentByIdResponse")]
        System.Threading.Tasks.Task<Api.DmsService.GetDocumentByIdResponse> GetDocumentByIdAsync(Api.DmsService.GetDocumentByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Ced.DocumentArchive.DmsService/IDmsService/GetDocumentsByIndeces", ReplyAction="http://Ced.DocumentArchive.DmsService/IDmsService/GetDocumentsByIndecesResponse")]
        Api.DmsService.GetDocumentsByIndecesResponse GetDocumentsByIndeces(Api.DmsService.GetDocumentsByIndecesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Ced.DocumentArchive.DmsService/IDmsService/GetDocumentsByIndeces", ReplyAction="http://Ced.DocumentArchive.DmsService/IDmsService/GetDocumentsByIndecesResponse")]
        System.Threading.Tasks.Task<Api.DmsService.GetDocumentsByIndecesResponse> GetDocumentsByIndecesAsync(Api.DmsService.GetDocumentsByIndecesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Ced.DocumentArchive.DmsService/IDmsService/SaveDocument", ReplyAction="http://Ced.DocumentArchive.DmsService/IDmsService/SaveDocumentResponse")]
        Api.DmsService.SaveDocumentResponse SaveDocument(Api.DmsService.SaveDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Ced.DocumentArchive.DmsService/IDmsService/SaveDocument", ReplyAction="http://Ced.DocumentArchive.DmsService/IDmsService/SaveDocumentResponse")]
        System.Threading.Tasks.Task<Api.DmsService.SaveDocumentResponse> SaveDocumentAsync(Api.DmsService.SaveDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Ced.DocumentArchive.DmsService/IDmsService/UpateDocument", ReplyAction="http://Ced.DocumentArchive.DmsService/IDmsService/UpateDocumentResponse")]
        Api.DmsService.UpateDocumentResponse UpateDocument(Api.DmsService.UpdateDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Ced.DocumentArchive.DmsService/IDmsService/UpateDocument", ReplyAction="http://Ced.DocumentArchive.DmsService/IDmsService/UpateDocumentResponse")]
        System.Threading.Tasks.Task<Api.DmsService.UpateDocumentResponse> UpateDocumentAsync(Api.DmsService.UpdateDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Ced.DocumentArchive.DmsService/IDmsService/DuplicateDocument", ReplyAction="http://Ced.DocumentArchive.DmsService/IDmsService/DuplicateDocumentResponse")]
        Api.DmsService.DuplicateDocumentResponse DuplicateDocument(Api.DmsService.DuplicateDocumentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Ced.DocumentArchive.DmsService/IDmsService/DuplicateDocument", ReplyAction="http://Ced.DocumentArchive.DmsService/IDmsService/DuplicateDocumentResponse")]
        System.Threading.Tasks.Task<Api.DmsService.DuplicateDocumentResponse> DuplicateDocumentAsync(Api.DmsService.DuplicateDocumentRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Ping", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PingRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Api.DmsService.PingRequest request;
        
        public PingRequest1() {
        }
        
        public PingRequest1(Api.DmsService.PingRequest request) {
            this.request = request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="PingResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class PingResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public Api.DmsService.PingResponse PingResult;
        
        public PingResponse1() {
        }
        
        public PingResponse1(Api.DmsService.PingResponse PingResult) {
            this.PingResult = PingResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IDmsServiceChannel : Api.DmsService.IDmsService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DmsServiceClient : System.ServiceModel.ClientBase<Api.DmsService.IDmsService>, Api.DmsService.IDmsService {
        
        public DmsServiceClient() {
        }
        
        public DmsServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DmsServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DmsServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DmsServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Api.DmsService.PingResponse1 Api.DmsService.IDmsService.Ping(Api.DmsService.PingRequest1 request) {
            return base.Channel.Ping(request);
        }
        
        public Api.DmsService.PingResponse Ping(Api.DmsService.PingRequest request) {
            Api.DmsService.PingRequest1 inValue = new Api.DmsService.PingRequest1();
            inValue.request = request;
            Api.DmsService.PingResponse1 retVal = ((Api.DmsService.IDmsService)(this)).Ping(inValue);
            return retVal.PingResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Api.DmsService.PingResponse1> Api.DmsService.IDmsService.PingAsync(Api.DmsService.PingRequest1 request) {
            return base.Channel.PingAsync(request);
        }
        
        public System.Threading.Tasks.Task<Api.DmsService.PingResponse1> PingAsync(Api.DmsService.PingRequest request) {
            Api.DmsService.PingRequest1 inValue = new Api.DmsService.PingRequest1();
            inValue.request = request;
            return ((Api.DmsService.IDmsService)(this)).PingAsync(inValue);
        }
        
        public Api.DmsService.GetDocumentByIdResponse GetDocumentById(Api.DmsService.GetDocumentByIdRequest request) {
            return base.Channel.GetDocumentById(request);
        }
        
        public System.Threading.Tasks.Task<Api.DmsService.GetDocumentByIdResponse> GetDocumentByIdAsync(Api.DmsService.GetDocumentByIdRequest request) {
            return base.Channel.GetDocumentByIdAsync(request);
        }
        
        public Api.DmsService.GetDocumentsByIndecesResponse GetDocumentsByIndeces(Api.DmsService.GetDocumentsByIndecesRequest request) {
            return base.Channel.GetDocumentsByIndeces(request);
        }
        
        public System.Threading.Tasks.Task<Api.DmsService.GetDocumentsByIndecesResponse> GetDocumentsByIndecesAsync(Api.DmsService.GetDocumentsByIndecesRequest request) {
            return base.Channel.GetDocumentsByIndecesAsync(request);
        }
        
        public Api.DmsService.SaveDocumentResponse SaveDocument(Api.DmsService.SaveDocumentRequest request) {
            return base.Channel.SaveDocument(request);
        }
        
        public System.Threading.Tasks.Task<Api.DmsService.SaveDocumentResponse> SaveDocumentAsync(Api.DmsService.SaveDocumentRequest request) {
            return base.Channel.SaveDocumentAsync(request);
        }
        
        public Api.DmsService.UpateDocumentResponse UpateDocument(Api.DmsService.UpdateDocumentRequest request) {
            return base.Channel.UpateDocument(request);
        }
        
        public System.Threading.Tasks.Task<Api.DmsService.UpateDocumentResponse> UpateDocumentAsync(Api.DmsService.UpdateDocumentRequest request) {
            return base.Channel.UpateDocumentAsync(request);
        }
        
        public Api.DmsService.DuplicateDocumentResponse DuplicateDocument(Api.DmsService.DuplicateDocumentRequest request) {
            return base.Channel.DuplicateDocument(request);
        }
        
        public System.Threading.Tasks.Task<Api.DmsService.DuplicateDocumentResponse> DuplicateDocumentAsync(Api.DmsService.DuplicateDocumentRequest request) {
            return base.Channel.DuplicateDocumentAsync(request);
        }
    }
}
